### PR TITLE
Fixed UserHandler crashing when SteamWeb is null

### PR DESCRIPTION
**Pull request by WildCard65**
Also re-added call to OnBotCreated

### CODE REVIEW

**Comment by BlueRaja** [comment]
GetUserHandler(NULL_STEAMID).OnBotCreated();

Same question as [here](https://github.com/Jessecar96/SteamBot/pull/617#issuecomment-69494508).

**Comment by WildCard65** [comment]
Continueing on from my answer on PR, OnBotCreated was placed in so bot coders can add in their custom logging objects to the bot's logging system(Which you suggested I add that method), and it fits to be called where bot is nearly fully constructed, but in bot's constructor is no valid steamid to use with GetUserHandler() so I had to create a "filler" SteamID object to be able to use GetUserHandler()

**Comment by BlueRaja** [comment]
Oh, hrm.  It causes an invalid `SteamID` to be passed into the constructor, which is a potentially breaking change.  We need to fix that.

**Comment by WildCard65** [comment]
the NULL_STEAMID object is only being used for OnBotCreated which I presume No one should be using bot logic other then adding custom logging objects in that method.

**Comment by BlueRaja** [comment]
It's [passed into the constructor](https://github.com/BlueRaja/SteamBot/blob/master/SteamBot/UserHandler.cs#L40) where it's subsequently [used to fetch the inventory](https://github.com/BlueRaja/SteamBot/blob/master/SteamBot/UserHandler.cs#L60).  We can't just fix the `UserHandler` to only fetch inventory when the `SteamID` is non-null, because custom user-handler constructors are passed it too.

**Comment by WildCard65** [comment]
K, I'll commit a fix for that.

**Comment by BlueRaja** [comment]
I *just* explained why that fix won't work...

**Pull request closed without merging**
