### PR TITLE
Inventory rewrite

### PR DESCRIPTION
**Pull request by WildCard65**
Recreating the recreate. But this time, this one does track.

### CODE REVIEW

**Comment by WildCard65** [comment]
@Bottswana @scholtzm Mind testing this?

**Comment by scholtzm** [comment]
This seems pretty massive. I don't even know where to start with testing. :smile:

**Comment by WildCard65** [comment]
@scholtzm tested this yet?

**Comment by scholtzm** [comment]
Unfortunately no. No time to test it right now, sorry. I wish we had at least some unit tests. :smile:

**Comment by WildCard65** [comment]
Merged the master repo in to keep PR in sync

**Comment by WildCard65** [comment]
@scholtzm @Bottswana @BlueRaja and suggestions for unit tests?

**Pull request closed without merging**
